-- BentoBox — Supabase Postgres schema
-- Paste this entire file into Supabase > SQL Editor > New Query > Run.
-- Safe to re-run: uses "if not exists" everywhere reasonable.

-- =========================================================
-- Master catalogs (shared across users; you maintain them)
-- =========================================================

create table if not exists proteins (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  category text,
  default_unit text not null default 'g',
  kcal_per_100g numeric not null,
  protein_g_per_100g numeric not null,
  carb_g_per_100g numeric not null,
  fat_g_per_100g numeric not null,
  shelf_life_days int default 4,
  created_at timestamptz default now()
);

create table if not exists carbs (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  type text not null,
  kcal_per_100g_dry numeric not null,
  protein_g_per_100g_dry numeric not null,
  carb_g_per_100g_dry numeric not null,
  fat_g_per_100g_dry numeric not null,
  created_at timestamptz default now()
);

create table if not exists veggies (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  kcal_per_100g numeric not null,
  protein_g_per_100g numeric not null,
  carb_g_per_100g numeric not null,
  fat_g_per_100g numeric not null,
  shelf_life_days int default 7,
  created_at timestamptz default now()
);

-- =========================================================
-- Purchases (price history log — append-only)
-- =========================================================

create table if not exists purchases (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade not null,
  item_type text not null check (item_type in ('protein','carb','veggie')),
  item_id uuid not null,
  store text not null check (store in ('Sams Club','Food Lion','Other')),
  amount_g numeric not null,
  total_price_cents int not null,
  is_mvp_discounted boolean default false,
  purchased_at date not null default current_date,
  created_at timestamptz default now()
);

create index if not exists idx_purchases_user_date on purchases(user_id, purchased_at desc);
create index if not exists idx_purchases_item on purchases(item_type, item_id);

-- =========================================================
-- Pantry (live remaining inventory)
-- =========================================================

create table if not exists pantry (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade not null,
  item_type text not null check (item_type in ('protein','carb','veggie')),
  item_id uuid not null,
  remaining_g numeric not null default 0,
  last_purchase_date date,
  unique(user_id, item_type, item_id)
);

-- =========================================================
-- Meals (the static template catalog generated by Claude)
-- =========================================================

create table if not exists meals (
  id uuid primary key default gen_random_uuid(),
  carb_id uuid references carbs(id),
  protein_id uuid references proteins(id) not null,
  veggie_id uuid references veggies(id) not null,
  name text not null,
  recipe_text text not null,
  prep_minutes int,
  vibe_tags text[] default '{}',
  meal_type text[] default '{dinner}',
  default_protein_g int default 170,
  default_carb_g int default 75,
  default_veggie_g int default 150,
  generated_at timestamptz default now(),
  unique(carb_id, protein_id, veggie_id, name)
);

-- =========================================================
-- Meal logs (decrements pantry)
-- =========================================================

create table if not exists meal_logs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade not null,
  meal_id uuid references meals(id),
  portions numeric not null default 1,
  protein_g_used numeric not null,
  carb_g_used numeric not null default 0,
  veggie_g_used numeric not null,
  eaten_at timestamptz default now()
);

create index if not exists idx_meal_logs_user_date on meal_logs(user_id, eaten_at desc);

-- =========================================================
-- Derived view: average cost per gram, per item, per user
-- =========================================================

create or replace view price_per_g as
select
  user_id,
  item_type,
  item_id,
  sum(total_price_cents)::numeric / nullif(sum(amount_g),0) as cents_per_g,
  max(purchased_at) as last_purchased,
  count(*) as purchase_count
from purchases
group by user_id, item_type, item_id;

-- =========================================================
-- Row Level Security
-- =========================================================

alter table purchases enable row level security;
alter table pantry enable row level security;
alter table meal_logs enable row level security;

drop policy if exists own_purchases on purchases;
drop policy if exists own_pantry on pantry;
drop policy if exists own_meal_logs on meal_logs;

create policy own_purchases on purchases for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy own_pantry    on pantry    for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy own_meal_logs on meal_logs for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

alter table proteins enable row level security;
alter table carbs enable row level security;
alter table veggies enable row level security;
alter table meals enable row level security;

drop policy if exists read_proteins on proteins;
drop policy if exists read_carbs on carbs;
drop policy if exists read_veggies on veggies;
drop policy if exists read_meals on meals;

create policy read_proteins on proteins for select using (true);
create policy read_carbs    on carbs    for select using (true);
create policy read_veggies  on veggies  for select using (true);
create policy read_meals    on meals    for select using (true);

-- =========================================================
-- Triggers: pantry stays in sync with purchases + meal logs
-- =========================================================

create or replace function bump_pantry_on_purchase()
returns trigger as $$
begin
  insert into pantry (user_id, item_type, item_id, remaining_g, last_purchase_date)
  values (new.user_id, new.item_type, new.item_id, new.amount_g, new.purchased_at)
  on conflict (user_id, item_type, item_id)
  do update set
    remaining_g = pantry.remaining_g + excluded.remaining_g,
    last_purchase_date = greatest(pantry.last_purchase_date, excluded.last_purchase_date);
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists after_purchase_insert on purchases;
create trigger after_purchase_insert
after insert on purchases
for each row execute function bump_pantry_on_purchase();

create or replace function decrement_pantry_on_meal_log()
returns trigger as $$
declare
  m record;
begin
  select carb_id, protein_id, veggie_id into m from meals where id = new.meal_id;

  update pantry
    set remaining_g = greatest(0, remaining_g - new.protein_g_used)
    where user_id = new.user_id and item_type = 'protein' and item_id = m.protein_id;

  if m.carb_id is not null and new.carb_g_used > 0 then
    update pantry
      set remaining_g = greatest(0, remaining_g - new.carb_g_used)
      where user_id = new.user_id and item_type = 'carb' and item_id = m.carb_id;
  end if;

  update pantry
    set remaining_g = greatest(0, remaining_g - new.veggie_g_used)
    where user_id = new.user_id and item_type = 'veggie' and item_id = m.veggie_id;

  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists after_meal_log_insert on meal_logs;
create trigger after_meal_log_insert
after insert on meal_logs
for each row execute function decrement_pantry_on_meal_log();
